name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:unit

    - name: Build
      run: npm run build

    - name: Build Docker image
      run: docker build -t vue-app:local .

    - name: Load image into Kind cluster
      run: |
        kind load docker-image vue-app:local --name vue-app-cluster
